title: Dmitry Strebkov

email: dmitry.strebkov@gmail.com
github_url: https://github.com/dstrebkov
linkedin_url: www.linkedin.com/in/dstrebkov
medium_url: https://medium.com
twitter_url: https://twitter.com

exclude: screenshots, LICENSE, README.md
markdown: kramdown
