title: Dmitry Strebkov

email: dstrebkov@gmail.com
github_url: https://github.com/dstrebkov
linkedin_url: https://linkedin.com
medium_url: https://medium.com
twitter_url: https://twitter.com

exclude: screenshots, LICENSE, README.md
markdown: kramdown
